name: CI/CD

on:
  push:
    branches-ignore: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build the image
        run: docker build -f Dockerfile.dev .
      - name: Run tests
        run: docker run -v /app/node_modules -v $(pwd):/app  a7c2f9897bd8 npm run test 

      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.dev
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
