name: CI/CD

on:
  push:
    branches-ignore: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the image
        run: docker build -f Dockerfile.dev -t wadahesam/frontend:latest .

      - name: Run tests
        # -e CI=true => this allows the test to exist after it runs
        run: docker run -e CI=true -v /app/node_modules -v $(pwd):/app wadahesam/frontend:latest npm run test 
